title: gbic-peer-instruction-2
hero_image: images/banner.png
description: gbic-peer-instruction-2 description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
